import { collection, nextId, nextDisplayOrder, sortByOrder } from './mongoHelpers.js';
import { generateUniqueSlug } from '../../utils/slug.js';
const categories = () => collection('categories');
async function slugExists(slug, excludeId) { return !!(await (await categories()).findOne({ slug, ...(excludeId ? { id: { $ne: excludeId } } : {}) })); }
async function withProductCount(row) { if (!row) return row; const count = await (await collection('products')).countDocuments({ category_id: row.id, published: true }); return { ...row, productCount: count }; }
export async function getAllCategories({ includeInactive = false } = {}) { const rows = await (await categories()).find(includeInactive ? {} : { active: true }).sort({ display_order: 1, name: 1 }).toArray(); const products = await (await collection('products')).find({ published: true }, { projection: { category_id: 1 } }).toArray(); const counts = products.reduce((map, p) => map.set(p.category_id, (map.get(p.category_id) || 0) + 1), new Map()); return rows.map((row) => ({ ...row, productCount: counts.get(row.id) || 0 })); }
export async function getCategoryTree(options = {}) { const flat = await getAllCategories(options); const byId = new Map(flat.map((c) => [c.id, { ...c, children: [] }])); const roots = []; for (const cat of byId.values()) { if (cat.parent_id && byId.has(cat.parent_id)) byId.get(cat.parent_id).children.push(cat); else roots.push(cat); } return roots; }
export async function getCategoryBySlug(slug) { return withProductCount(await (await categories()).findOne({ slug })); }
export async function getCategoryById(id) { return withProductCount(await (await categories()).findOne({ id })); }
export async function getCategoryAncestry(id) { const chain = []; let current = await getCategoryById(id); const seen = new Set(); while (current && !seen.has(current.id)) { seen.add(current.id); chain.unshift(current); current = current.parent_id ? await getCategoryById(current.parent_id) : null; } return chain; }
export async function getSubcategoryIds(categoryId) { const ids = [categoryId]; const children = await (await categories()).find({ parent_id: categoryId }, { projection: { id: 1 } }).toArray(); for (const child of children) ids.push(...await getSubcategoryIds(child.id)); return ids; }
export async function createCategory(data) { const slug = await generateUniqueSlug(data.slug || data.name, slugExists); const category = { id: await nextId('categories'), parent_id: data.parentId || null, name: data.name, slug, description: data.description || '', image: data.image || '', accent_color: data.accentColor || '#1a6b3a', display_order: data.displayOrder ?? await nextDisplayOrder('categories'), active: data.active !== false, seo_title: data.seoTitle || '', seo_description: data.seoDescription || '', og_image: data.ogImage || '', created_at: new Date(), updated_at: new Date() }; await (await categories()).insertOne(category); return withProductCount(category); }
export async function updateCategory(id, data) { const existing = await getCategoryById(id); if (!existing) return null; const slug = data.slug && data.slug !== existing.slug ? await generateUniqueSlug(data.slug, slugExists, id) : existing.slug; const updated = { ...existing, parent_id: data.parentId ?? existing.parent_id, name: data.name ?? existing.name, slug, description: data.description ?? existing.description, image: data.image ?? existing.image, accent_color: data.accentColor ?? existing.accent_color, display_order: data.displayOrder ?? existing.display_order, active: data.active !== undefined ? data.active : existing.active, seo_title: data.seoTitle ?? existing.seo_title, seo_description: data.seoDescription ?? existing.seo_description, og_image: data.ogImage ?? existing.og_image, updated_at: new Date() }; await (await categories()).replaceOne({ id }, updated); return withProductCount(updated); }
export async function deleteCategory(id) { const productCount = await (await collection('products')).countDocuments({ category_id: id }); const childCount = await (await categories()).countDocuments({ parent_id: id }); if (productCount) return { success: false, message: `Cannot delete: ${productCount} product(s) are assigned to this category. Reassign or delete them first.` }; if (childCount) return { success: false, message: `Cannot delete: ${childCount} subcategory(ies) exist under this category. Delete or reassign them first.` }; await (await categories()).deleteOne({ id }); return { success: true }; }
export async function reorderCategories(orderedIds) { const store = await categories(); await Promise.all(orderedIds.map((id, index) => store.updateOne({ id }, { $set: { display_order: index } }))); }
