import { collection, nextId, nextDisplayOrder } from './mongoHelpers.js';
import { generateUniqueSlug } from '../../utils/slug.js';
import { getSubcategoryIds } from './categoryRepo.js';
const products = () => collection('products');
const normalizeId = (id) => {
  const value = Number(id);
  return Number.isFinite(value) && String(value) === String(id).trim() ? value : id;
};
async function slugExists(slug, excludeId) { return !!(await (await products()).findOne({ slug, ...(excludeId ? { id: { $ne: normalizeId(excludeId) } } : {}) })); }
function output(product, category) { if (!product) return null; const images = (product.images || []).slice().sort((a, b) => Number(b.isPrimary) - Number(a.isPrimary) || a.displayOrder - b.displayOrder); const specifications = (product.specifications || []).filter((a) => a.value && String(a.value).trim()); return { ...product, tags: Array.isArray(product.tags) ? product.tags : String(product.tags || '').split(',').map((tag) => tag.trim()).filter(Boolean), images, specifications, category: category ? { id: category.id, name: category.name, slug: category.slug } : null }; }
async function attach(product) { const category = product?.category_id ? await (await collection('categories')).findOne({ id: normalizeId(product.category_id) }) : null; return output(product, category); }
export async function listProducts({ categoryId, categorySlug, search, featured, latest, published = true, sort = 'display_order', page = 1, limit = 24, tags } = {}) { const filter = {}; if (published !== 'all') filter.published = !!published; let categoryIds; if (categorySlug) { const category = await (await collection('categories')).findOne({ slug: categorySlug }); categoryIds = category ? await getSubcategoryIds(category.id) : [-1]; } else if (categoryId) categoryIds = await getSubcategoryIds(categoryId); if (categoryIds) filter.category_id = { $in: categoryIds }; if (featured) filter.featured = true; if (latest) filter.is_latest = true; if (search?.trim()) { const regex = new RegExp(search.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'); filter.$or = [{ name: regex }, { description: regex }, { short_description: regex }, { tags: regex }, { 'specifications.name': regex }, { 'specifications.value': regex }]; } if (tags) filter.tags = { $regex: (Array.isArray(tags) ? tags : [tags]).map((tag) => tag.trim()).join('|'), $options: 'i' }; const ordering = { display_order: { display_order: 1, name: 1 }, 'name-asc': { name: 1 }, 'name-desc': { name: -1 }, newest: { created_at: -1 }, 'price-asc': { price_min: 1 }, 'price-desc': { price_max: -1 }, featured: { featured: -1, display_order: 1 } }[sort] || { display_order: 1, name: 1 }; const total = await (await products()).countDocuments(filter); const rows = await (await products()).find(filter).sort(ordering).skip((Math.max(1, Number(page)) - 1) * Number(limit)).limit(Number(limit)).toArray(); return { data: await Promise.all(rows.map(attach)), pagination: { total, page: Number(page), limit: Number(limit), totalPages: Math.ceil(total / Number(limit)) || 1 } }; }
export async function getProductBySlug(slug, { publishedOnly = true } = {}) { return attach(await (await products()).findOne({ slug, ...(publishedOnly ? { published: true } : {}) })); }
export async function getProductById(id) { return attach(await (await products()).findOne({ id: normalizeId(id) })); }
export async function incrementViewCount(id) { await (await products()).updateOne({ id: normalizeId(id) }, { $inc: { view_count: 1 } }); }
export async function getRelatedProducts(product, limit = 6) { const filter = { id: { $ne: normalizeId(product.id) }, published: true }; if (product.category_id) filter.category_id = normalizeId(product.category_id); const same = await (await products()).find(filter).sort({ display_order: 1 }).limit(limit).toArray(); return Promise.all(same.map(attach)); }
export async function getFilterFacets({ categorySlug } = {}) { const options = categorySlug ? { categorySlug } : {}; const result = await listProducts({ ...options, limit: 10000 }); const facets = {}; for (const product of result.data) for (const row of product.specifications || []) (facets[row.label] ||= new Set()).add(row.rawValue || row.value); return Object.fromEntries(Object.entries(facets).map(([key, value]) => [key, [...value].sort()])); }
function fields(data, existing = {}) { return { category_id: data.categoryId ?? existing.category_id ?? null, name: data.name ?? existing.name, short_description: data.shortDescription ?? existing.short_description ?? '', description: data.description ?? existing.description ?? '', price_min: data.priceMin ?? existing.price_min ?? null, price_max: data.priceMax ?? existing.price_max ?? null, price_unit: data.priceUnit ?? existing.price_unit ?? 'Meter', moq_value: data.moqValue ?? existing.moq_value ?? '', moq_unit: data.moqUnit ?? existing.moq_unit ?? 'Meter', tags: Array.isArray(data.tags) ? data.tags.join(',') : data.tags ?? existing.tags ?? '', published: data.published !== undefined ? !!data.published : existing.published !== false, featured: data.featured !== undefined ? !!data.featured : !!existing.featured, is_latest: data.isLatest !== undefined ? !!data.isLatest : !!existing.is_latest, display_order: data.displayOrder ?? existing.display_order ?? 0, seo_title: data.seoTitle ?? existing.seo_title ?? '', seo_description: data.seoDescription ?? existing.seo_description ?? '', og_image: data.ogImage ?? existing.og_image ?? '' }; }
function normalizeImages(images = []) { return images.map((image, index) => ({ id: image.id || `${Date.now()}-${index}`, url: image.url, altText: image.altText || '', isPrimary: !!image.isPrimary || index === 0, displayOrder: index })); }
function normalizeSpecs(attributes = []) { return attributes.map((attribute, index) => ({ id: attribute.id || `${Date.now()}-${index}`, label: attribute.label || attribute.name, rawValue: attribute.rawValue ?? attribute.value, value: attribute.value ?? attribute.rawValue, unit: attribute.unit || '', displayOrder: index })).filter((attribute) => attribute.label && attribute.value !== undefined && String(attribute.value).trim()); }
export async function createProduct(data) { const product = { id: await nextId('products'), slug: await generateUniqueSlug(data.slug || data.name, slugExists), ...fields(data), images: normalizeImages(data.images), specifications: normalizeSpecs(data.specifications || data.attributes), view_count: 0, created_at: new Date(), updated_at: new Date() }; await (await products()).insertOne(product); return getProductById(product.id); }
export async function updateProduct(id, data) { const normalizedId = normalizeId(id); const existing = await (await products()).findOne({ id: normalizedId }); if (!existing) return null; const updated = { ...existing, ...fields(data, existing), slug: data.slug && data.slug !== existing.slug ? await generateUniqueSlug(data.slug, slugExists, normalizedId) : existing.slug, images: Array.isArray(data.images) ? normalizeImages(data.images) : existing.images, specifications: Array.isArray(data.specifications || data.attributes) ? normalizeSpecs(data.specifications || data.attributes) : existing.specifications, updated_at: new Date() }; await (await products()).replaceOne({ id: normalizedId }, updated); return getProductById(normalizedId); }
export async function deleteProduct(id) { await (await products()).deleteOne({ id: normalizeId(id) }); return { success: true }; }
export async function duplicateProduct(id) { const original = await getProductById(id); if (!original) return null; return createProduct({ ...original, categoryId: original.category_id, name: `${original.name} (Copy)`, published: false, featured: false, isLatest: false, tags: original.tags, specifications: original.specifications }); }
export async function reorderProducts(orderedIds) { const store = await products(); await Promise.all(orderedIds.map((id, index) => store.updateOne({ id: normalizeId(id) }, { $set: { display_order: index } }))); }
export async function setProductImages(productId, images) { await (await products()).updateOne({ id: normalizeId(productId) }, { $set: { images: normalizeImages(images), updated_at: new Date() } }); }
export async function setProductAttributes(productId, attributes) { await (await products()).updateOne({ id: normalizeId(productId) }, { $set: { specifications: normalizeSpecs(attributes), updated_at: new Date() } }); }
export async function getDashboardStats() { const store = await products(); const [totalProducts, publishedProducts, featuredProducts, totalCategories, totalTestimonials, totalEnquiries, newEnquiries, mostViewed] = await Promise.all([store.countDocuments(), store.countDocuments({ published: true }), store.countDocuments({ featured: true }), (await collection('categories')).countDocuments(), (await collection('testimonials')).countDocuments(), (await collection('enquiries')).countDocuments(), (await collection('enquiries')).countDocuments({ status: 'New' }), store.find({}, { projection: { id: 1, name: 1, slug: 1, view_count: 1 } }).sort({ view_count: -1 }).limit(5).toArray()]); return { totalProducts, publishedProducts, featuredProducts, totalCategories, totalTestimonials, totalEnquiries, newEnquiries, mostViewed }; }
