CREATE TABLE IF NOT EXISTS categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer REFERENCES categories(id) ON DELETE SET NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  image text NOT NULL DEFAULT '',
  accent_color text NOT NULL DEFAULT '#1a6b3a',
  display_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  seo_title text NOT NULL DEFAULT '',
  seo_description text NOT NULL DEFAULT '',
  og_image text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories(slug);

CREATE TABLE IF NOT EXISTS products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer REFERENCES categories(id) ON DELETE SET NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  short_description text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  price_min numeric,
  price_max numeric,
  price_unit text NOT NULL DEFAULT 'Meter',
  moq_value text NOT NULL DEFAULT '',
  moq_unit text NOT NULL DEFAULT 'Meter',
  tags text NOT NULL DEFAULT '',
  published boolean NOT NULL DEFAULT true,
  featured boolean NOT NULL DEFAULT false,
  is_latest boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  seo_title text NOT NULL DEFAULT '',
  seo_description text NOT NULL DEFAULT '',
  og_image text NOT NULL DEFAULT '',
  view_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_featured ON products(featured);
CREATE INDEX IF NOT EXISTS idx_products_published ON products(published);
CREATE INDEX IF NOT EXISTS idx_products_published_display_order ON products(published, display_order);
CREATE INDEX IF NOT EXISTS idx_products_category_published ON products(category_id, published);

CREATE INDEX IF NOT EXISTS idx_testimonials_published ON testimonials(published, display_order);
CREATE INDEX IF NOT EXISTS idx_testimonials_display_order ON testimonials(display_order DESC);
CREATE INDEX IF NOT EXISTS idx_enquiries_status ON enquiries(status);
CREATE INDEX IF NOT EXISTS idx_enquiries_status_created_at ON enquiries(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_enquiries_created_at ON enquiries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contacts_status ON contacts(status);
CREATE INDEX IF NOT EXISTS idx_contacts_status_created_at ON contacts(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON contacts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_homepage_sections_order ON homepage_sections(display_order);
CREATE INDEX IF NOT EXISTS idx_navigation_items_order ON navigation_items(display_order);
CREATE INDEX IF NOT EXISTS idx_navigation_items_parent ON navigation_items(parent_id);

CREATE TABLE IF NOT EXISTS product_images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  url text NOT NULL,
  alt_text text NOT NULL DEFAULT '',
  display_order integer NOT NULL DEFAULT 0,
  is_primary boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images(product_id);

CREATE TABLE IF NOT EXISTS product_attributes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  name text NOT NULL,
  value text NOT NULL,
  unit text NOT NULL DEFAULT '',
  display_order integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_product_attributes_product ON product_attributes(product_id);

CREATE TABLE IF NOT EXISTS testimonials (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL,
  role text NOT NULL DEFAULT '',
  quote text NOT NULL,
  image text NOT NULL DEFAULT '',
  rating integer NOT NULL DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  published boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS enquiries (
  id text PRIMARY KEY, name text, company text, email text, phone text,
  country text, product text, product_id integer, category text, category_id integer,
  quantity numeric, unit text NOT NULL DEFAULT 'Meter', purpose text,
  requirements text, attachment text, source_page text,
  status text NOT NULL DEFAULT 'New', created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS contacts (
  id text PRIMARY KEY, name text, email text, phone text, message text,
  status text NOT NULL DEFAULT 'New', created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_settings (key text PRIMARY KEY, value text);

CREATE TABLE IF NOT EXISTS navigation_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer REFERENCES navigation_items(id) ON DELETE CASCADE,
  label text NOT NULL, link text NOT NULL DEFAULT '', display_order integer NOT NULL DEFAULT 0,
  visible boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS homepage_sections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_key text NOT NULL UNIQUE, title text NOT NULL DEFAULT '', subtitle text NOT NULL DEFAULT '',
  content jsonb NOT NULL DEFAULT '{}'::jsonb, enabled boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS admin_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE NOT NULL, password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'super_admin', created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS website_visits (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL,
  path text NOT NULL DEFAULT '/',
  referrer text NOT NULL DEFAULT '',
  user_agent text NOT NULL DEFAULT '',
  visited_date date NOT NULL DEFAULT CURRENT_DATE,
  visited_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, path, visited_date)
);

CREATE INDEX IF NOT EXISTS idx_website_visits_date ON website_visits(visited_date DESC);
CREATE INDEX IF NOT EXISTS idx_website_visits_session ON website_visits(session_id);

CREATE TABLE IF NOT EXISTS audit_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text, action text, entity text, entity_id text, old_value jsonb, new_value jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);